DROP TABLE IF EXISTS ANIMAL_TYPES;

CREATE TABLE ANIMAL_TYPES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE VETS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  vet_name VARCHAR(250) NOT NULL
);

CREATE TABLE ANIMALS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  animal_name VARCHAR(250) NOT NULL,
  vet_id INT NOT NULL,
  animal_type_id INT NOT NULL,
  FOREIGN KEY (vet_id) references VETS(id),
  FOREIGN KEY (animal_type_id) references ANIMAL_TYPES(id)
);

CREATE TABLE APPOINTMENTS (
 id INT AUTO_INCREMENT PRIMARY KEY,
 animal_id INT NOT NULL,
 start_time VARCHAR NOT NULL,
 FOREIGN KEY (animal_id) REFERENCES ANIMALS(id)
)

